# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Fiasy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
        pod 'Firebase/Auth'
        pod 'Firebase/Core'
        pod 'Fabric'
        pod 'Crashlytics'
        pod 'Firebase/Messaging'
        pod 'FirebaseInstanceID'
        pod 'Alamofire'
        pod 'AlamofireImage'
        pod 'Parchment'
        pod 'MBCircularProgressBar'

        pod 'FacebookCore'
        pod 'FacebookLogin'
        pod 'FacebookShare'
        pod 'Firebase/Core'
        pod 'Firebase/Auth'
        
        pod 'GoogleSignIn'
        
        pod 'Moya'
        pod 'RxSwift'
        pod 'RxCocoa'
        pod 'Swinject'
        pod 'Moya/RxSwift'
        pod 'ViperMcFlurry'
        pod 'RealmSwift'
        pod 'ObjectMapper'
        pod 'SwinjectStoryboard'
        pod 'Moya-ObjectMapper/RxSwift'

        pod 'FacebookSDK'
        pod 'FacebookSDK/LoginKit'
        pod 'FacebookSDK/ShareKit'
        pod 'FacebookSDK/PlacesKit'
        pod 'FBSDKMessengerShareKit'
        pod 'OneSignal'
        pod 'Bolts'
        pod 'FBSDKCoreKit'
        pod 'FBSDKLoginKit'
        pod 'Bugsee'
        pod 'NVActivityIndicatorView'
        pod 'Firebase/Database'
        pod 'MaterialControls'
        pod 'SwiftyJSON'
        pod 'DropDown'
        pod 'BEMCheckBox'
        pod 'Kingfisher'
        pod 'SwiftEntryKit', '1.0.4'
        
        pod 'Amplitude-iOS'
        pod 'Adjust'
        pod 'AMPopTip'
        pod 'SQLite.swift'
        pod 'GradientProgressBar'
        pod 'DynamicBlurView'
        pod 'Firebase/Storage'
        pod 'ReachabilitySwift'
        pod 'TagListView'
        pod 'XLPagerTabStrip'
        pod 'AMDots'
        pod 'VisualEffectView'
        pod 'NextGrowingTextView'
        pod 'UITextView+Placeholder'
        pod 'UICircularProgressRing'
        pod 'Charts'
        
 end
